### ISSUE TITLE
koolproxyR 你使用了什么魔法编译的时候没了

### ISSUE THREAD

**Issue by brianzc0306** [Beginner-Go/my-packages#1]
你使用了什么魔法编译的时候没了呀 编译的时候没选项

**Comment by Beginner-Go** [comment]
最近在重写Makefile, bug较多

**Comment by brianzc0306** [comment]
ERROR: please fix feeds/test/luci-app-koolproxyR/Makefile - see logs/feeds/test/luci-app-koolproxyR/dump.txt for details
出来了这个

**Comment by brianzc0306** [comment]
> 最近在重写Makefile, bug较多

ERROR: please fix feeds/test/luci-app-koolproxyR/Makefile - see logs/feeds/test/luci-app-koolproxyR/dump.txt for details

**Comment by Beginner-Go** [comment]
> > 最近在重写Makefile, bug较多
> 
> ERROR: please fix feeds/test/luci-app-koolproxyR/Makefile - see logs/feeds/test/luci-app-koolproxyR/dump.txt for details

在修了，进度：新建文件夹
